eslogan:
  es: Sanando con amor y alegría
descriptorLogotipo: FELICIDAD QUE SIRVE
contacto:
  correo: ''
  telefono: ''
  whatsapp: ''
  correoInstitucional: ''
redes:
  facebook: ''
  instagram: ''
  youtube: ''
  linkedin: ''
  tiktok: ''
donataria:
  discriminant: false
avisoDePrivacidad: ''
