eslogan:
  es: Sanando con amor y alegría
descriptorLogotipo: FELICIDAD QUE SIRVE
descripcionBreve:
  es: >-
    Humanizamos la experiencia hospitalaria a través del clown care certificado.
    Doctor Payaso A.C., México.
contacto:
  correo: mexico@doctorpayaso.com
  telefono: +52 55 3899 9466
  whatsapp: '+525538999466'
  correoInstitucional: mexico@doctorpayaso.com
redes:
  facebook: https://www.facebook.com/doctorpayasoac
  instagram: https://www.instagram.com/doctorpayaso.ac
  youtube: https://www.youtube.com/@DoctorPayaso
  linkedin: https://www.linkedin.com/company/doctorpayaso
  tiktok: https://www.tiktok.com/@doctorpayaso
donataria:
  discriminant: false
