eslogan:
  es: Sanar con Amor y Alegría.
descriptorLogotipo: Doctor Payaso A.C.
descripcionBreve:
  es: >-
    Doctor Payaso A.C.


    Somos una comunidad de personas formadas para acompañar a quienes atraviesan
    momentos de vulnerabilidad a través del juego, la escucha y la conexión
    humana.


    Llevamos el corazón en la punta de la nariz.
contacto:
  correo: mexico@doctorpayaso.com
  telefono: +52 55 3899 9466
  whatsapp: '+525538999466'
  correoInstitucional: mexico@doctorpayaso.com
redes:
  facebook: https://www.facebook.com/doctorpayasoac/
  instagram: https://www.instagram.com/doctorpayaso.ac
  youtube: www.youtube.com/@DoctorPayaso
  linkedin: https://www.linkedin.com/company/doctor-payaso-a.c./
  tiktok: https://www.linkedin.com/company/doctor-payaso-a.c./
donataria:
  discriminant: false
